stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

maven:build-job:
  stage: build
  image: maven:3.6.3-jdk-11
  script:
    - mvn clean package

# A simple comment
build-job:  # This job runs in the build stage, which runs first.
  image: docker@sha256:c8bb6fa5388b56304dd770c4bc0478de81ce18540173b1a589178c0d31bfce90
  services:
    - docker:dind@sha256:c8bb6fa5388b56304dd770c4bc0478de81ce18540173b1a589178c0d31bfce90  
  stage: build
  script:
    - docker build -t registry.gitlab.com/wgu-gitlab-environment/student-repos/gsmi572/d424-software-engineering-capstone .
    - docker login registry.gitlab.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push registry.gitlab.com/wgu-gitlab-environment/student-repos/gsmi572/d424-software-engineering-capstone


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  
 
  script:
    - echo "Deploying application..."
    - curl -X POST $DEPLOY_HOOK_URL
    - echo "Application successfully deployed."

  only:
      - D424

